# Generated by Django 4.2.25 on 2025-11-27 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
        migrations.DeleteModel(
            name='PsychologistProfile',
        ),
    ]
