# Generated by Django 4.2.25 on 2025-11-30 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_dialogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychologist_dialogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
