# Generated by Django 4.2.25 on 2025-11-29 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_add_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
