# Generated by Django 4.2.25 on 2025-11-29 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_alter_user_avatar'),
        ('booking', '0003_booking_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='duration',
        ),
        migrations.AlterField(
            model_name='booking',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='authorization.psychologist'),
        ),
    ]
