# Generated by Django 4.2.25 on 2025-11-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_duration_alter_booking_psychologist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'В процесі'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено'), ('canceled', 'Скасовано'), ('completed', 'Завершено')], default='pending', max_length=20),
        ),
    ]
