# Generated by Django 4.2.25 on 2025-11-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Стаж (років)'),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='languages',
            field=models.CharField(blank=True, max_length=100, verbose_name='Мови'),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='response_time',
            field=models.CharField(blank=True, max_length=20, verbose_name='Час відповіді'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
