# Generated by Django 4.2.25 on 2025-11-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologist',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='format',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='price',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='response_time',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='tz',
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
