# Generated by Django 4.2.25 on 2025-11-26 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_remove_psychologist_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tz',
        ),
    ]
