# Generated by Django 4.2.25 on 2025-11-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(
                default='profiles/default_avatar.png',
                upload_to='profiles/'
            ),
        ),
    ]
