# Generated by Django 4.2.25 on 2025-11-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='cancel_policy',
            field=models.CharField(choices=[('24_hours', 'За 24 години'), ('12_hours', 'За 12 годин'), ('6_hours', 'За 6 годин')], default='24_hours', max_length=255),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='consultation_format',
            field=models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн'), ('both', 'Онлайн та офлайн')], default='online', max_length=50),
        ),
    ]
