# Generated by Django 4.2.25 on 2025-11-27 20:46

import authorization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_psychologist_cancel_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='work_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='profiles/default_avatar.png', upload_to=authorization.models.avatar_upload_path),
        ),
    ]
