# Generated by Django 4.2.25 on 2025-11-29 18:08

import authorization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_psychologist_experience_psychologist_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='profiles/media/default_avatar.png', upload_to=authorization.models.avatar_upload_path),
        ),
    ]
