# Generated by Django 4.2.25 on 2025-11-30 19:59

import authorization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/avatars/default_avatar.png', upload_to=authorization.models.avatar_upload_path),
        ),
    ]
